// src/renderer/components/molecules/Counter/Counter.tsx
/** @jsx jsx */
import { css, jsx } from "@emotion/react";
import type { FunctionComponent, HTMLAttributes } from "react";

import Button from "~/renderer/components/atoms/Button";

interface ICounterType extends HTMLAttributes<HTMLDivElement> {
  onDecrease?: () => void;
  onIncrease?: () => void;
}
const Counter: FunctionComponent<ICounterType> = ({
  children,
  onDecrease,
  onIncrease,
  ...props
}) => (
  <div className="counter" {...props}>
    <Button primary className="counter__decrease-btn" onClick={onDecrease}>
      -
    </Button>
    <span
      css={css`
        padding: 0 5px;
        @media (prefers-color-scheme: dark) {
          color: white;
        }
        @media (prefers-color-scheme: light) {
          color: black;
        }
      `}
      className="counter__text"
    >
      {children}
    </span>
    <Button primary className="counter__increase-btn" onClick={onIncrease}>
      +
    </Button>
  </div>
);

export default Counter;

// src/renderer/components/molecules/Counter/Counter.vue
<template>
  <div class="counter">
    <Button class="counter__decrease-button" primary @click="onDecrement"
      >-</Button
    >
    <span class="counter__text">
      <slot />
    </span>
    <Button class="counter__increase-button" primary @click="onIncrement"
      >+</Button
    >
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Button from "~/renderer/components/atoms/Button";
export default defineComponent({
  components: { Button },
  emits: ["decrement", "increment"],
  setup(_, { emit }) {
    const onDecrement = () => emit("decrement");
    const onIncrement = () => emit("increment");
    return {
      onDecrement,
      onIncrement,
    };
  },
});
</script>

<style lang="scss" scoped>
.counter__text {
  padding: 0 5px;
  @media (prefers-color-scheme: dark) {
    color: white;
  }
  @media (prefers-color-scheme: light) {
    color: black;
  }
}
</style>
