// src/renderer/components/atoms/Button/Button.tsx
/** @jsx jsx */
import { css, jsx, useTheme } from "@emotion/react";
import type { ButtonHTMLAttributes, FunctionComponent } from "react";

interface IButtonTypes extends ButtonHTMLAttributes<HTMLButtonElement> {
  primary?: boolean;
}
const Button: FunctionComponent<IButtonTypes> = ({
  children,
  primary = false,
  ...props
}) => {
  const theme = useTheme();
  return (
    <button
      className="button"
      css={css`
        background-color: ${primary ? theme.colors.primary : "black"};
        padding: 5px 10px;
        border: 1px solid black;
        position: relative;
        cursor: pointer;
        &:after {
          content: "";
          position: absolute;
          height: 100%;
          width: 100%;
          background-color: white;
          left: 0;
          top: 0;
          opacity: 0;
        }
        &:hover:after {
          opacity: 0.3;
        }
        &:focus {
          outline: 0;
        }
      `}
      {...props}
    >
      {children}
    </button>
  );
};

export default Button;

// src/renderer/components/atoms/Button/Button.vue
<template>
  <button class="button" :class="{ 'button--primary': primary }">
    <slot />
  </button>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    primary: Boolean,
  },
});
</script>

<style lang="scss" scoped>
.button {
  &--primary {
    background-color: var(--app-primary);
  }
  padding: 5px 10px;
  border: 1px solid black;
  position: relative;
  cursor: pointer;
  &:after {
    content: "";
    position: absolute;
    height: 100%;
    width: 100%;
    background-color: white;
    left: 0;
    top: 0;
    opacity: 0;
  }
  &:hover:after,
  &:focus:after {
    opacity: 0.3;
    outline: 0;
  }
}
</style>
